### PR TITLE
changed mongodb uri

### PR DESCRIPTION
**Pull request by eddypjr**

### CODE REVIEW

**Review by astaiglesia — APPROVED** [review]
approved

**Review by phillipkb — APPROVED** [review]

**Review by phillipkb — APPROVED** [review]
looks good!

**Review by bubakarrr — APPROVED** [review]

**Review by koderka2020 — APPROVED** [review]
all approved, new mongoDB set up

**Comment by koderka2020** [comment]
First merge to upstream main- New mongoDB link working

**Pull request merged**
